//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.AppData
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public register()
        {
            this.service_register = new HashSet<service_register>();
        }
    
        public int id_register { get; set; }
        public int id_client { get; set; }
        public int id_apartment { get; set; }
        public System.DateTime date_register { get; set; }
        public System.DateTime date_out { get; set; }


        public virtual apartment apartment { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_register> service_register { get; set; }
    }
}
