//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_register
    {
        public int id_register { get; set; }
        public int id_service { get; set; }
        public int kolvo { get; set; }

        public virtual register register { get; set; }
        public virtual service service { get; set; }
    }
}
